builds:
  - id: http-checker
    main: .
    user: 65532:65532
    flags:
      - -trimpath
    env:
      - KO_DOCKER_REPO=harbor.powerbot.energy/utilities
defaultPlatforms:
- linux/arm64
- linux/amd64